### ISSUE TITLE
Install Can Fail If The User Has A .wgetrc File Set

### ISSUE THREAD

**Issue by hexxellor** [vitadev/vdpm#10]
If the user has a .wgetrc file (wget Startup File) set, those settings can cause the "install-all.sh" script to fail.

I didn't look in to it too much but it was failing to download the correct files from SourceForge and instead was downloading the HTML page and saving it with a goofy name. I have attached an example .wgetrc file that causes the install to fail.

Simply renaming the .wgetrc file before install allows it to successfully install.

I was hoping that there was a switch on wget to allow the ignoring of that file but it doesn't appear to have one or I missed it because I'm an idiot. I don't know that messing with the user's .wgetrc is a good idea since it could be in one of many locations or ever installed by the admin, in which case you wouldn't have access to alter/rename it so I'm guessing a simple warning on the README.md would be best.

[wgetrc.txt](https://github.com/vitadev/vdpm/files/416475/wgetrc.txt)

**Comment by joshdekock** [comment]
Thanks for the heads up, I'll add the warning soon™ (you could also submit a PR)
