### ISSUE TITLE
compilation terminated - How can i fix this ?

### ISSUE THREAD

**Issue by 0Hidder** [vitadev/vdpm#8]
freetype-2.6.5
=> OK
=> Running: ./configure
=> Running: make  -j4 DESTDIR= PREFIX=/usr/local/vitasdk/arm-vita-eabi prefix=/usr/local/vitasdk/arm-vita-eabi exec_prefix=/usr/local/vitasdk/arm-vita-eabi
=> Make stage failed :(
=> Dumping vdpm_make.log to stdout
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Iinclude -I/usr/local/vitasdk/arm-vita-eabi/include/freetype2 -ffat-lto-objects -flto   -c -o source/vita2d.o source/vita2d.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Iinclude -I/usr/local/vitasdk/arm-vita-eabi/include/freetype2 -ffat-lto-objects -flto   -c -o source/vita2d_texture.o source/vita2d_texture.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Iinclude -I/usr/local/vitasdk/arm-vita-eabi/include/freetype2 -ffat-lto-objects -flto   -c -o source/vita2d_draw.o source/vita2d_draw.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Iinclude -I/usr/local/vitasdk/arm-vita-eabi/include/freetype2 -ffat-lto-objects -flto   -c -o source/utils.o source/utils.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Iinclude -I/usr/local/vitasdk/arm-vita-eabi/include/freetype2 -ffat-lto-objects -flto   -c -o source/vita2d_image_png.o source/vita2d_image_png.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Iinclude -I/usr/local/vitasdk/arm-vita-eabi/include/freetype2 -ffat-lto-objects -flto   -c -o source/vita2d_image_jpeg.o source/vita2d_image_jpeg.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Iinclude -I/usr/local/vitasdk/arm-vita-eabi/include/freetype2 -ffat-lto-objects -flto   -c -o source/vita2d_image_bmp.o source/vita2d_image_bmp.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -Iinclude -I/usr/local/vitasdk/arm-vita-eabi/include/freetype2 -ffat-lto-objects -flto   -c -o source/vita2d_font.o source/vita2d_font.c
source/vita2d_font.c:5:32: fatal error: freetype2/ft2build.h: No such file or directory
 #include <freetype2/ft2build.h>
                                

compilation terminated.
make: *** [ < builtin >: source/vita2d_font.o] Error 1
make: **   Waiting for unfinished jobs....

![sem titulo](https://cloud.githubusercontent.com/assets/20892290/17562872/3492a382-5f03-11e6-8db3-4a1030d48d8a.png)

**Comment by joshdekock** [comment]
Same issue as #7

**Comment by Melon-Bread** [comment]
Switching to config.travis on MSYS2 leads to cmake issues
http://hastebin.com/rupoyejodo.sh

**Comment by joshdekock** [comment]
@Melon-Bread Make sure you're using the latest git master

**Comment by Melon-Bread** [comment]
> Make sure you're using the latest git master
@joshdekock I am. This was from a fresh cloned repo from a hour before I posted.
